// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwN7hf_c2WYwvmlr_MdQ_18eQfauLRWQ',
    appId: '1:49616297399:web:394561e0c2b9cfbf0e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    authDomain: 'deneme2-bc96d.firebaseapp.com',
    storageBucket: 'deneme2-bc96d.appspot.com',
    measurementId: 'G-NCK304NX28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TJtwhUHcA1zwq_9N2vE_F_L6-TjHSEA',
    appId: '1:49616297399:android:18224109b20d14500e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    storageBucket: 'deneme2-bc96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNFyAxaGJH0mHl-Mot3PYe5c462D_vLc',
    appId: '1:49616297399:ios:4cfea5d2aa82f2370e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    storageBucket: 'deneme2-bc96d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNFyAxaGJH0mHl-Mot3PYe5c462D_vLc',
    appId: '1:49616297399:ios:4cfea5d2aa82f2370e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    storageBucket: 'deneme2-bc96d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgwN7hf_c2WYwvmlr_MdQ_18eQfauLRWQ',
    appId: '1:49616297399:web:032a8e3089b1e56f0e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    authDomain: 'deneme2-bc96d.firebaseapp.com',
    storageBucket: 'deneme2-bc96d.appspot.com',
    measurementId: 'G-KPQ4Q36N3Q',
  );
}
